### ISSUE TITLE
Refactor Rectangle::translate to modify the rectangle in-place instead of returning a copy

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#1001] opened 2021-11-09 16:24 UTC
`Rectangle::translate` currently returns a copy of the moved rectangle. This is un-intuitive. Instead, it should modify the rectangle in-place.

If you want a copy of a moved rectangle, just use the constructor.

**Comment by DanRStevens** [comment] 2021-11-10 00:43
This is very much by design. The typical case where I see this being used would be on `const` objects, where you can't use a mutator method. Modifying the method would make it impossible to use on such objects. For this case, it wouldn't be appropriate to provide const and mutable overloads, since that would make it very easy to modify an object by accident when you wanted a modified copy. You'd have to use `const_cast` or assign to `const &` variables to control which method was selected.

If we implement #704, it would be very easy to translate a `Rectangle` in-place without method support, since you'd have direct access to a `Point` object for the origin. I think that would be the better way to go about providing mutable translate support.

From an efficiency perspective, I doubt there is much difference either way. `Rectangle` is a fairly small and cheap object to create. I think the main concern here is usability and correctness, and that's going to depend on context.

**Closed** 2021-11-24 00:12 UTC
