### ISSUE TITLE
Bug in `split` method when `skip_empty = false` with a trailing delimiter

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#198] opened 2019-05-20 22:27 UTC
There is a bug in `split` as illustrated by the commented out unit test line:
```cpp
	// EXPECT_EQ((NAS2D::StringList{"abc", ""}), NAS2D::split("abc,", ',', false));  // Actual: {"abc"}
```

It seems the `split` method doesn't respect the `bool skip_empty` parameter when it is `false` and there is a trailing delimiter.

For reference:
[`std::getline`](https://en.cppreference.com/w/cpp/string/basic_string/getline)
[`std::basic_ios::operator bool`](https://en.cppreference.com/w/cpp/io/basic_ios/operator_bool)

The code in question:
```cpp
	while (std::getline(ss, curString, delim))
	{
		if (skip_empty && curString.empty()) { continue; }
		result.push_back(curString);
	}
```
When no characters are extracted, `std::getline` sets the `failbit`. The `std::getline` method returns the input stream. The input stream is converted to a `bool` for the `while` test. The `operator bool` on the `stringstream`/`istringstream` returns `!fail()`. Hence, when no data is extracted the `std::getline` effectively returns `false`, even when a delimiter was present.

**Comment by cugone** [comment] 2019-05-21 04:04
Splitting off the `bool` argument into two methods might make this more clear.

Reaching the end of the stream is a different condition than extracting nothing due to the delimiter being reached. This is standard and intended behavior, Preventing this behavior will require a check after the stream has failed due to EOF and checking if the last character is the delimiter:


    //Inside splitSkipEmpty
    //...
    while (std::getline(ss, curString, delim))
    {
        if(curString.empty()) { continue; }
        result.push_back(curString);
    }
    //Only add empty string if reached end vs any other failure.
    if(ss.eof() && (ss.str().back() == delim))
    {
        result.push_back(std::string{});
    }
    //...

**Comment by DanRStevens** [comment] 2019-05-21 07:26
Agreed that addressing #199 first would make this more clear.

----

I'm not sure about appealing to the CSV specification here. There are plenty of comma separated data sets, which don't necessarily conform to the CSV standard. The name of the method itself has no implication of CSV formatted data.

In terms of the CSV specification, I assume you mean:

> 4.  Within the header and each record, there may be one or more
       fields, separated by commas.  Each line should contain the same
       number of fields throughout the file.  Spaces are considered part
       of a field and should not be ignored.  The last field in the
       record must not be followed by a comma.  For example:
>
>     aaa,bbb,ccc

In the above case, I read the example as having 3 fields. However, if all rows were to have 4 fields, and the last field happened to be an empty string, I believe the above implies that the following is valid:
```
aaa,bbb,ccc,ddd
eee,fff,ggg,
```

In that case, the second row ended with a comma, though the comma was actually before the empty 4th field, and not trailing after some last 3rd field.

I still think there is a bug here.

----

In terms of efficiency, you can check against the `str` variable, rather than calling `ss.str()` to generate a new string.

**Comment by cugone** [comment] 2019-05-22 15:39
The way split works does not use "header" fields it just splits on the given delimiter. It's up to the business rules to account for headers.

Your example:

    aaa,bbb,ccc,ddd
    eee,fff,ggg,

when input into the split function would actually produce as output:

    { "aaa", "bbb", "ccc", "ddd<newline>eee", "fff", "ggg" }

**Comment by DanRStevens** [comment] 2019-05-22 16:38
Yes indeed. I'd like a method that makes as few assumptions as possible, so the higher level code can decide how things should work.

In the case of my example, I was assuming doing a line by line split from within a loop. That would result in the following calls:
```cpp
split("aaa,bbb,ccc,ddd", ',', false); // Expected: {"aaa", "bbb", "ccc", "ddd"}
split("eee,fff,ggg,", ',', false); // Expected: {"eee", "fff", "ggg", ""} (according to me)
```
In such as setup, if the data has a consistent number of delimiters, the output will also have a consistent number of data items, even if the last field happens to be blank. It already works that way for blank fields in other positions:
```cpp
split(",x,y,z", ',', false); // Expected: {"", "x", "y", "z"}
```

**Comment by cugone** [comment] 2019-05-23 14:01
Ran equivalent code in javascript and a trailing delimiter creates an empty string. Re-marked as bug. Awaiting Acceptance and Merge of #213 before pushing fix.

**Closed** 2019-05-25 16:04 UTC
Labels: bug
