### ISSUE TITLE
Rationale for PhysFS use?

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#118] opened 2019-04-03 17:19 UTC
I'm interested in developing a preliminary DirectX11 renderer for your engine intending to use it with OPHD and like that you are using modern C++. I was wondering what your rationale for using PhysFS is?

I just tried to directly use the source code of PhysFS (3.0.2) in one of my own projects so as to not create an external dependency and it does not compile cleanly on a W4 level with warnings as errors in both VS2019 and VS2017 x64 build (There are hundreds). I spent an hour just getting rid of all the warnings (with pragma warning disable directives) and the few casts needed for type size and signed/unsigned mismatches. Not to mention there are unused variables all over the place and redefinition errors in a few places. It is decidedly not a C++-minded library and is poorly written.

**Comment by DanRStevens** [comment] 2019-04-03 23:09
Hi cugone, welcome.

You are right that PhysFS is not really a C++ library. Most of it's source code is plain C, and the API interface is plain C. That can make it's use from C++ seem like a bit of an archaic style.

----

In terms of compiling and errors, I can't say too much about the Windows side or MSVC, but I can speak a little about the Linux side.

We are using the native PhysFS build scripts packaged with the library, and so I'm not seeing any errors or warnings compiling.

As a check though, I tried running the PhysFS sources manually though the compiler with the `-fsyntax-only` option to check the source for errors. The following produce no warnings or errors:
```
# Both C and C++ sources
gcc -fsyntax-only *.c *.cpp
clang -fsyntax-only *.c *.cpp

# C++ sources only
g++ -fsyntax-only *.cpp
clang++ -fsyntax-only *.cpp
```

If however I try to process the `.c` files as C++, that does produce warnings and errors:
```
# C sources as C++
g++ -fsyntax-only *.c
clang++ -fsyntax-only *.c
```

As the PhysFS project is predominantly C (not C++), perhaps the errors you are seeing come from processing the C source code as C++? I don't know how well MSVC handles straight C code, if it detects based on file extension, or if it needs any special flags set. On the Linux side, I'm aware of the base compiler names (`gcc`, `clang`) setting the language based on file extension. Explicitly using a language specific name (`g++`, `clang++`) disables that auto detection.

Additionally, if header files are processed directly by the compiler as source files (rather than being included by them), that can also lead to errors and warnings:
```
gcc -fsyntax-only *.h
clang -fsyntax-only *.h
```
In particular, I'm seeing a lot of errors involving `size_t` and the basic type typedefs (`PHYSFS_uint32`, etc.).

Maybe also check that header files are added as header files, and not as "source files". If you try to add a header file as a source file, I think MSVC will try to compile it directly, which it shouldn't be doing.

----

In terms of dependency management, I'd highly recommend using a package system whenever possible. This is often the easiest approach. We've had some good experiences with NuGet packages, though sometimes the packages are a bit old. If you need newer packages, I'd recommend a small script for your project that downloads all dependent source packages and runs them through their compile and install steps. Only as a last resort would I include the source directly in my own repository. Though yes, I recognize that is the easy way to get started, especially if you haven't mucked around with build systems. Build systems can be hard.

----

Finally, there has actually been some informal discussion about possibly handling the file access without PhysFS. There are no immediate plans to swap it out though, and we haven't committed one way or the other. For now we're sticking with maintenance to keep a working system, and slow iterative improvements.

**Comment by cugone** [comment] 2019-04-04 00:24
Thanks for the write-up.

Do you use PhysFS strictly for controlling access above the working directory the executable is in? If so, this is an easy fix and does not need the use of PhysFS...at least in Windows.

I avoid build systems for ease of transferability, custom source changes (Dear Imgui is a good example), and I stay up-to-date on Modern C++ while tools tend not to (all new code must be written with the most recent stable version of the language: Brand new code: c++17, if a tool doesn't support it, don't use the tool.)

I forgot to mention I have the language set to c++17 so most of the warnings were "if expression is constant, consider using if constexpr".

MSVC by default compiles as C or C++ based on the file extension. You can force it to compile as C or C++ by either changing the file properties directly (not scalable) or "including" the .c file inside a .cpp file and compiling that. This also allows you to disable warnings en-masse via push and pop.

**Comment by ldicker83** [comment] 2019-04-04 01:34
The intention to use PhysicsFS was to provide transparent/seamless archive 'streaming', kind of like what Quake2 and Quake3 do. As a side note, it was a historical choice from when NAS2D was still in its infancy circa 2008/2009.

In the long run the plan is to remove PhysFS as a dependency and instead take advantage of C++11 - C++17 filesystem functions and objects instead. PhysFS served its purpose but for NAS2D based applications I don't see a need to have support for Doom WAD, Quake 2 PAK, Descent HOG etc. etc. archives. ZIP archives are enough and are generally trivial to implement.

**Comment by cugone** [comment] 2019-04-04 01:51
@ldicker83 That's commendable, but I foresee issues trying to use std::filesystem if you move away from C++17 and the only reason is "because TravisCI doesn't support it." as the std::filesystem only just moved out of the experimental namespace in October. In this case it will be way less of a hassle to just scrap PhysFS now.

Looking over the Filesystem code, it is trivial to implement all the functions as delegate calls to std::filesystem functions and std::filesystem::path objects. It will also make all of the code immediately cross-platform.

**Comment by ldicker83** [comment] 2019-04-04 03:15
Most of the NAS2D::Filesystem code is pretty trivial, it effectively wraps the most basic FS operations and PhysicsFS calls within a C++ class. I don't expect it to be much effort to convert it to std::filesystem. The problem is that std::filesystem is not yet supported by default on macOS X (this may have changed in the last few months, I haven't yet checked).

Long story short, it's "in the works" so to speak. I have higher priorities for now but I would like to drop the dependency (especially since it pulls in a lot of code that never actually gets executed, leads to binary bloat).

**Comment by cugone** [comment] 2019-04-04 14:38
Create a PR for updating to VS17 (eventually to VS19), It builds locally just fine, but I have no experience in Linux-based build systems, so if accepted some things will need changing to get it to build on the worker VMs for AppVeyor. TravisCI is a wash because its Windows support is in its infancy as reported on their website.

**Comment by DanRStevens** [comment] 2019-04-05 12:26
> Do you use PhysFS strictly for controlling access above the working directory the executable is in?
No. That is one aspect of it. Some concerns are:
1) Read only access to static resources alongside the exe and in subfolders
2) Setting a platform specific write folder (manual with `<filesystem>`, and different for each system)
3) Restricting writes to a given subtree (a potential security concern, which `<filesystem>` has no equivalent for)
4) Automatic mounting of archive files (need an external library for this)
5) Prioritized file access over a virtual filesystem (again, no real equivalent here, so manual code)

Not all are equally important, but they are all at least somewhat relevant.

----

> In this case it will be way less of a hassle to just scrap PhysFS now.
I don't follow the argument here. I think scrapping use of PhysFS right now is actually quite the hassle. This is particularly true for non-Windows platforms.

I think we're still far away from being able to do a clean tested transition. Despite how trivial the changes may appear on the surface, they will have rippling consequences. Further, these changes are at the core of many cross platform issues, and so need testing on all platforms.

Right now we have absolutely no tests for the filesystem code. Having code that merely compiles cleanly isn't enough. It has to actually work. And we won't know that unless the code actually runs on all systems. And the details will be different on every system.

> It will also make all of the code immediately cross-platform.
Except that it won't, because `<filesystem>` support is still lacking on some platforms and compilers. Additionally, `<filesystem>` doesn't encompass the same scope as PhysFS, meaning custom code which has to be built and tested from scratch.

The new `<filesystem>` code is wonderful. Except that's it's kind of not, because it's roll out has been dragging on for years, leaving everyone hopeful yet frustrated.

----

> especially since it pulls in a lot of code that never actually gets executed, leads to binary bloat
I haven't tested, but from what I heard, modern linkers will cut out most of the bloat from unused code. They're supposed to be pretty good at that now. Early linkers were not.

But yes, it would be nice to have fewer dependencies.

**Comment by cugone** [comment] 2019-04-05 14:55
> 
>     1. Read only access to static resources alongside the exe and in subfolders
> 

Can you give an example of intent? Do you not want users to be able to alter resources like images and text files and such? Why? If the user screws with your resources and it breaks the game, it's not your concern.

---

>
>     2. Setting a platform specific write folder (manual with `<filesystem>`, and different for each system)
>

Like Windows' AppData folder but for Mac and Linux as well? 

--- 

>
>     3. Restricting writes to a given subtree (a potential security concern, which `<filesystem>` has no equivalent for)
>

Why? A game shouldn't care where the resources come from (save files, images, scripts, etc) just as long as they are validated before being loaded; This also cannot be prevented, all the user has to to is turn off your game and then they can do whatever they want to your file structure. The only real way to mitigate this is discipline and consistency of where game files are stored and *automatically* written to/read from. Manually reading/writing resources (save games) can come from anywhere. See UE4's concept of a "Content" subfolder. Nothing outside this folder is packaged as a game-specific resource and most save games are written to/read from the AppData or other "known" equivalent folder.

---

> 
>     4. Automatic mounting of archive files (need an external library for this)
> 

By "automatic" do you mean transparent structures that read from archives as if they are real folder structures?

If so, yes, this can't be helped, but there are specialized libraries that do *just* that and nothing else; zLib for example, and you can easily just drop in code that can be compiled along-side your code in a Thirdparty folder (TinyXml2, Dear Imgui, STBI) so there's no *external* dependency. DLLs next to the executable for said libraries is something that can't be helped (fmod, libcurl, I'm looking at you!). There's no need to pull in and download a whole library just to get your code to compile and link. Users (including down-stream games you yourself write) just need to have your top-level Engine code folder referenced properly and any .dlls and it will compile and link.

---

>
>     5. Prioritized file access over a virtual filesystem (again, no real equivalent here, so manual code)
>

I don't understand what you mean, again, could you give an example?

---

> 
> I don't follow the argument here. I think scrapping use of PhysFS right now is actually quite the hassle. This is particularly true for non-Windows platforms.
> 

With this I agree. I'm just now finding out that Apple is a horrible platform to develop for and Linux is a little better. Reason being is Microsoft has active and direct participation in the C++ committees, helping shape the language. They have the most stable releases (and it's easier to tell what each release has available because it correlates with major IDE versions) with library and language updates happening at the same time; Linux doesn't update the Library changes at the same time and you have to manually link specific library changes and implementations with confusing argument names. Apple just doesn't do any of that and is off in their own world of "We'll release changes whenever, even if they are years behind anyone else." In all the CppCon, CppNow, and other C++ convention videos I've seen not one that has been a developer working in a Mac-based IDE environment (Xcode). All Linux, Clang, GCC or Visual Studio (even VS for Mac!).

---

> I think we're still far away from being able to do a clean tested transition. Despite how trivial the changes may appear on the surface, they will have rippling consequences. Further, these changes are at the core of many cross platform issues, and so need testing on all platforms.
> 
> Right now we have absolutely no tests for the filesystem code. Having code that merely compiles cleanly isn't enough. It has to actually work. And we won't know that unless the code actually runs on all systems. And the details will be different on every system.
> 

I think this is a separate issue. Removing unneeded dependencies on external libraries, getting every platform on the same page compile-wise is the first step, (at this stage there's a lot of do-nothing or well-defined values that are returned and documented functions, but your interfaces are complete. Then writing OS-specific implementations behind those interfaces if need be.

---

>
> > It will also make all of the code immediately cross-platform.
> 
> Except that it won't, because `<filesystem>` support is still lacking on some platforms and compilers. Additionally, `<filesystem>` doesn't encompass the same scope as PhysFS, meaning custom code which has to be built and tested from scratch.
> 
> The new `<filesystem>` code is wonderful. Except that's it's kind of not, because it's roll out has been dragging on for years, leaving everyone hopeful yet frustrated.
> 

See my previous about Apple. 🙁 

---

>
> > especially since it pulls in a lot of code that never actually gets executed, leads to binary bloat
> 
> I haven't tested, but from what I heard, modern linkers will cut out most of the bloat from unused code. They're supposed to be pretty good at that now. Early linkers were not.
> 
> But yes, it would be nice to have fewer dependencies.

No argument here.

---

All-in-all if you look at the statistics (derived from Steam hardware & software surveys) 96% of gamers are on a Windows platform, 3% are on Mac and 0.8% are on Linux. Most games on Steam are windows-only. Trying to be cross-platform up front with such low market share is just a waste of resources and time. Get it working on Windows, then dedicate time as needed porting the OS-specific implementations of your interface.

**Comment by DanRStevens** [comment] 2019-05-06 10:24
My apologies for not replying sooner. I got kind of busy last month, and this sort of fell by the wayside.

> >  1. Read only access to static resources alongside the exe and in subfolders
>
> Can you give an example of intent? Do you not want users to be able to alter resources like images and text files and such? Why? If the user screws with your resources and it breaks the game, it's not your concern.

This one is more concerned about finding the static data packaged with the executable file. The executable could potentially be installed or unpacked anywhere. The static data resources distributed with the game are likely to be located at some relative path from the executable file, typically a subfolder. This is more about finding the current executable's location, so the path to the subfolder can be found. This is not as simple as just assuming the current working directory points to the executable's folder, as that is often not the case. For example, starting an executable in the terminal using an absolute or relative path will leave the current working directory untouched. Ex:
```
/path/to/some/working/folder/ $ /game/path/executable
Current working directory: /path/to/some/working/folder/
Executable path: /game/path/
Possible resource path: /game/path/data/
```

Finding the current executable's location has different solutions for different platforms. It's also complicated by symbolic links, where the executable path might have a component pointing to another area of the filesystem. One common way of finding executable location is using `argv[0]`.

In terms of security concerns, that's more about number 3. Though that concern doesn't really apply to the static data. The static data is of course assumed to be static. If the user edits it outside of the game, that's their problem/benefit.

> > 2. Setting a platform specific write folder (manual with `<filesystem>`, and different for each system)
>
> Like Windows' AppData folder but for Mac and Linux as well?

Yes, exactly. Examples from the PhysFS documentation:
```
Windows: "C:\\Users\\bob\\AppData\\Roaming\\My Company\\My Program Name"
Linux: "/home/bob/.local/share/My Program Name"
MacOS: "/Users/bob/Library/Application Support/My Program Name"
```

> > 3. Restricting writes to a given subtree (a potential security concern, which `<filesystem>` has no equivalent for)
>
> Why? A game shouldn't care where the resources come from (save files, images, scripts, etc) just as long as they are validated before being loaded; This also cannot be prevented, all the user has to to is turn off your game and then they can do whatever they want to your file structure. The only real way to mitigate this is discipline and consistency of where game files are stored and automatically written to/read from. Manually reading/writing resources (save games) can come from anywhere. See UE4's concept of a "Content" subfolder. Nothing outside this folder is packaged as a game-specific resource and most save games are written to/read from the AppData or other "known" equivalent folder.

Many games allow for sharing of resources during online play. For instance, automatically downloading a new map file from a game host. Normally you'd just dump this into a 3rd party map folder. Example: `gameWriteFolder/downloadedMaps/mapName.map`. However, if some hacker kid gets clever and decides to name his map something like `../../../../../../command.com`, you may end up with a problem. This is a particular concern on single user setups where people regularly use an admin account for normal tasks. That used to be common on Windows, though thankfully security has gotten a bit better by default.

Ideally writes should be restricted to a game specific write folder, and any attempt to escape that write folder should either fail or at least be ignored. PhysFS handles this with it's virtual filesystem concept. You can mount multiple folders for reading, including static read-only game assets, but have a single write folder, typically set as in number 2 above. The game effectively can't see any of the real filesystem that hasn't been mounted into the virtual filesystem. There is no way to map a malicious map name like the above to a potentially dangerous area of the filesystem, even if the user was running as an admin.

> > 4. Automatic mounting of archive files (need an external library for this)
>
> By "automatic" do you mean transparent structures that read from archives as if they are real folder structures?
>
> If so, yes, this can't be helped, but there are specialized libraries that do just that and nothing else; zLib for example, and you can easily just drop in code that can be compiled along-side your code in a Thirdparty folder (TinyXml2, Dear Imgui, STBI) so there's no external dependency. DLLs next to the executable for said libraries is something that can't be helped (fmod, libcurl, I'm looking at you!). There's no need to pull in and download a whole library just to get your code to compile and link. Users (including down-stream games you yourself write) just need to have your top-level Engine code folder referenced properly and any .dlls and it will compile and link.

I think you've got a pretty good handle on the challenges there. The effective proposal here, is to replace one dependency with another lower level dependency, albeit with lighter requirements and a more specific focus.

I wouldn't recommend direct source inclusion though. I think whenever possible, a package manager solution should be preferred. To avoid external DLLs, static libraries can be used. It increases the executable size, but makes things more standalone.

> > 5. Prioritized file access over a virtual filesystem (again, no real equivalent here, so manual code)
>
> I don't understand what you mean, again, could you give an example?

With PhysFS you can mount multiple folders into a common point of the virtual filesystem. That means two real filesystem paths might map to the same virtual filesystem path. This isn't a requirement per se, rather how things are done with PhysFS. It can potentially be used for mod support. If a mod folder is mounted, and has a higher priority than a core game asset folder, then the mod assets will be seen instead of the core game assets. That may be one way to allow for mods to work.

Example:
```
filesystem.mount("/", "data/coreAssets/");  // Contains "assetName1", and "assetName2"
filesystem.mount("/", "modName/newAssets/");  // Also contains "assetName1"
data1 = filesystem.read("assetName1");  // Core game asset or mod asset?
data2 = filesystem.read("assetName2");  // Core game asset
```
Here two real filesystem folders are mounted to the root of the virtual filesystem. Assuming the second mount folder has a higher priority, then any access to "assetName1" will get the mod version of it, rather than the packaged core game asset.

Note that "assetName2" is not hidden by the mod folder mount. Rather the virtual filesystem overlays the mod folder onto the filesystem image. Files with the same name in the original folders are hidden by the new assets in the mod folder. Other files which are not overlaid are still present and accessible under their usual name. This is the priority part.

Again, there are alternative ways to do this, and no requirement that we handle such things in the PhysFS way.

**Comment by DanRStevens** [comment] 2020-01-31 03:27
I think this discussion can be wrapped up. Multiple issues have spawned from this discussion. A summary and link to other issues can be found in #379.

**Closed by DanRStevens** 2020-01-31 03:27 UTC
Labels: discussion
