### ISSUE TITLE
Reorganize Renderer folder file layout

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#976] opened 2021-08-30 05:15 UTC
There are several math classes that have nothing to do with the Renderer living in the Renderer folder. This is confusing. Moving them into a dedicated `Math` folder would be helpful.

**Comment by ldicker83** [comment] 2021-09-27 22:49
I would generally agree with this. Kind of grew organically but it's time to clean it up.

**Comment by DanRStevens** [comment] 2021-09-28 07:01
Duplicate of #358.

**Closed** 2021-09-28 07:01 UTC
