### ISSUE TITLE
Create NuGet package for NAS2D

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#125] opened 2019-04-05 03:23 UTC
I was thinking, we should look into creating a NuGet package for the NAS2D library. Such a package would make distribution and use easier for other people.

**Comment by ldicker83** [comment] 2019-04-06 18:26
Yes it would. Now that I'm getting more familiar with it, I've seen how this makes things much less painful.

**Comment by cugone** [comment] 2019-04-06 20:29
Here are some resources for creating/installing a NuGet package and getting the references correct.
 - https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package
 - https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio
 - https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui
 - https://docs.microsoft.com/en-us/nuget/consume-packages/ways-to-install-a-package

**Comment by ldicker83** [comment] 2019-05-02 22:27
I'm more apt to move forward with vcpkg instead only because nuget was designed for .net more so than native packages. The downside with vcpkg is that for CI it will end up recompiling every time a build is updated.

I'm not opposed to nuget, just unconvinced it's correct for NAS2D's native... ness. Will continue to research.

**Comment by DanRStevens** [comment] 2019-05-06 11:26
It seems `vcpkg` is capable of pre-built binary packages:
https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md

It kind of sounds like it can package things into a NuGet package.

I'm rather liking the experience with `vcpkg`. The one downside is it's not quite as integrated with the toolchain as NuGet. It's close though. In particular, there is no project file integration, and it won't automatically install all dependencies needed for a project when a new developer downloads the source, or when a developer moves to a new machine. The install commands with `vcpkg` aren't hard, but there is still the mental hurdle of opening a terminal and installing each of the needed packages, plus the mental hurdle of installing `vcpkg` in the first place. I can see that easily being a deterrent for some people to get started.

It looks like the NuGet mechanism to integrate into the project file uses generic project file features. There may be a way to integrate the `vcpkg` install into the project file through a similar mechanism.

Not sure if this is related but there is some mention of integrating `vcpkg` with a project file. I get the sense this is different though, and they have an interesting warning about not doing this with open source projects:
https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md#linking-nuget-file

**Comment by cugone** [comment] 2020-01-27 13:55
Closing due to move to `vcpkg`

**Closed by cugone** 2020-01-27 13:55 UTC

**Comment by DanRStevens** [comment] 2020-01-27 19:34
Just a small clarification, the project dependencies have been ported from NuGet to vcpkg. That covers project inputs. This issue is more focused on project outputs. I suppose the equivalent would be to package this project using vcpkg, though NuGet, or multiple package managers, could still be an option.

Currently we are using Git submodules to pull in this dependency in downstream projects. That has some negative implications for build time. With NuGet or vcpkg, the caching done for the CI builds would help reduce build time. It is however a fairly reasonable way to handle things currently. The NAS2D dependency is under more heavy development than downstream projects, and we aren't doing versioned releases presently.

At any rate, packing outputs isn't a pressing need. We have a system that currently works. The build time isn't horrible. It would take time to research and implement packaging. I'm fine with not having an open issue to address a potentially nice to have feature.
